"use client";

import { useEffect, useState } from "react";
import Sidebar from "@/components/Sidebar";

type ReportData = { summary: { mentions: number; engagement: number; negative_mentions: number; tracked_keywords: number }; sentiment: { sentiment: string; count: number }[]; platforms: { platform: string; count: number }[]; risks: { id: number; content: string | null; platform: string; matched_keyword: string; sentiment: string; scraped_at: string }[] };

export default function ExecutiveReportsPage() {
  const [data, setData] = useState<ReportData | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { fetch("/api/analytics/executive").then(async (response) => { const body = await response.json(); if (!response.ok) setError(body.error || "Unable to load analytics."); else setData(body); }).catch(() => setError("Unable to load analytics.")); }, []);
  return <div className="min-h-screen lg:pl-64"><Sidebar /><main className="mx-auto min-h-screen max-w-[1200px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="mb-8"><p className="eyebrow">Leadership view</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-900">Executive intelligence</h1><p className="mt-2 text-sm text-slate-500">A concise view of conversation volume, engagement, sentiment, and emerging risk.</p></header>{error && <div className="panel mb-6 p-4 text-sm text-red-700">{error}</div>}{data && <><div className="grid gap-4 sm:grid-cols-4">{[["Mentions", data.summary.mentions], ["Engagement", data.summary.engagement], ["Negative mentions", data.summary.negative_mentions], ["Tracked keywords", data.summary.tracked_keywords]].map(([label, value]) => <div className="panel p-5" key={label}><p className="eyebrow">{label}</p><p className="mt-3 text-3xl font-semibold text-slate-900">{value}</p></div>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="panel p-6"><p className="eyebrow">Sentiment mix</p><div className="mt-5 space-y-3">{data.sentiment.map((item) => <div className="flex justify-between text-sm" key={item.sentiment}><span className="capitalize">{item.sentiment}</span><strong>{item.count}</strong></div>)}</div></section><section className="panel p-6"><p className="eyebrow">Source coverage</p><div className="mt-5 space-y-3">{data.platforms.map((item) => <div className="flex justify-between text-sm" key={item.platform}><span className="capitalize">{item.platform.replace("_", " ")}</span><strong>{item.count}</strong></div>)}</div></section></div><section className="panel mt-6 p-6"><p className="eyebrow">Risk watchlist</p><div className="mt-5 space-y-3">{data.risks.length ? data.risks.map((risk) => <article className="rounded-xl bg-slate-50 p-4" key={risk.id}><div className="flex justify-between gap-4 text-xs text-slate-500"><span>{risk.platform} - {risk.matched_keyword}</span><span>{new Date(risk.scraped_at).toLocaleDateString()}</span></div><p className="mt-2 text-sm text-slate-800">{risk.content || "Flagged mention without text."}</p></article>) : <p className="text-sm text-slate-500">No negative or spam signals found.</p>}</div></section></>}</main></div>;
}
