"use client";

import { FormEvent, useEffect, useState } from "react";
import Sidebar from "@/components/Sidebar";

export default function IntegrationsPage() {
  const [data, setData] = useState<{ keys: { id: number; name: string; key_prefix: string; created_at: string }[]; webhooks: { id: number; name: string; endpoint_url: string; events: string[]; enabled: boolean }[] }>({ keys: [], webhooks: [] });
  const [keyName, setKeyName] = useState("");
  const [webhook, setWebhook] = useState({ name: "", endpointUrl: "" });
  const [secret, setSecret] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  async function load() { const response = await fetch("/api/integrations"); const result = await response.json(); if (!response.ok) setError(result.error); else setData(result); }
  useEffect(() => { load(); }, []);
  async function createKey(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/integrations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "key", name: keyName }) }); const result = await response.json(); if (!response.ok) setError(result.error); else { setSecret(result.key); setKeyName(""); await load(); } }
  async function createWebhook(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/integrations", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "webhook", ...webhook }) }); const result = await response.json(); if (!response.ok) setError(result.error); else { setSecret(result.secret); setWebhook({ name: "", endpointUrl: "" }); await load(); } }
  async function remove(type: string, id: number) { await fetch(`/api/integrations?type=${type}&id=${id}`, { method: "DELETE" }); await load(); }
  return <div className="min-h-screen lg:pl-64"><Sidebar /><main className="mx-auto min-h-screen max-w-[1100px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="mb-8"><p className="eyebrow">Developer tools</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-900">Integrations</h1><p className="mt-2 text-sm text-slate-500">Create organization API keys and signed webhook endpoints for downstream systems.</p></header>{error && <div className="mb-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{secret && <div className="mb-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><strong>Copy this secret now:</strong><code className="mt-2 block break-all">{secret}</code><button onClick={() => setSecret(null)} className="mt-3 text-xs font-semibold underline">Dismiss</button></div>}<div className="grid gap-6 md:grid-cols-2"><section className="panel p-6"><p className="eyebrow">API access</p><h2 className="mt-1 text-lg font-semibold text-slate-900">Keys</h2><form onSubmit={createKey} className="mt-5 flex gap-2"><input required className="field" placeholder="Analytics integration" value={keyName} onChange={(e) => setKeyName(e.target.value)} /><button className="rounded-xl bg-blue-600 px-4 py-2 text-xs font-semibold text-white">Create</button></form><div className="mt-5 space-y-2">{data.keys.map((key) => <div key={key.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-xs"><span>{key.name} · {key.key_prefix}…</span><button onClick={() => remove("key", key.id)} className="font-semibold text-red-600">Revoke</button></div>)}</div></section><section className="panel p-6"><p className="eyebrow">Event delivery</p><h2 className="mt-1 text-lg font-semibold text-slate-900">Webhooks</h2><form onSubmit={createWebhook} className="mt-5 space-y-3"><input required className="field" placeholder="Webhook name" value={webhook.name} onChange={(e) => setWebhook({ ...webhook, name: e.target.value })} /><input required type="url" className="field" placeholder="https://example.com/events" value={webhook.endpointUrl} onChange={(e) => setWebhook({ ...webhook, endpointUrl: e.target.value })} /><button className="w-full rounded-xl bg-slate-900 px-4 py-2 text-xs font-semibold text-white">Register webhook</button></form><div className="mt-5 space-y-2">{data.webhooks.map((hook) => <div key={hook.id} className="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-xs"><span className="truncate">{hook.name} · {hook.endpoint_url}</span><button onClick={() => remove("webhook", hook.id)} className="font-semibold text-red-600">Delete</button></div>)}</div></section></div></main></div>;
}
