"use client";

import { useEffect, useState } from "react";
import Sidebar from "@/components/Sidebar";

type Data = { summary: { users: number; organizations: number; posts: number; open_tickets: number }; users: { id: number; name: string; email: string; is_super_admin: boolean; created_at: string; organization_count: number; organization_name: string | null }[]; organizations: { id: number; name: string; slug: string; created_at: string; member_count: number; post_count: number }[] };

export default function SuperAdminPage() {
  const [data, setData] = useState<Data | null>(null);
  const [error, setError] = useState<string | null>(null);
  useEffect(() => { fetch("/api/super-admin", { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error); setData(body); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Unable to load admin console.")); }, []);
  return <div className="min-h-screen lg:pl-60"><Sidebar /><main className="mx-auto min-h-screen max-w-[1400px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="mb-8"><p className="eyebrow">Platform control</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-900 dark:text-white">Super admin console</h1><p className="mt-2 text-sm text-slate-500 dark:text-slate-400">Global visibility across users, customer workspaces, collected data, and support operations.</p></header>{error && <div className="panel p-5 text-sm text-red-600">{error}</div>}{data && <><div className="mb-6 grid grid-cols-2 gap-3 lg:grid-cols-4">{[["Users", data.summary.users], ["Organizations", data.summary.organizations], ["Collected posts", data.summary.posts], ["Open tickets", data.summary.open_tickets]].map(([label, value]) => <div key={String(label)} className="panel p-4"><p className="eyebrow">{label}</p><p className="mt-2 text-2xl font-semibold text-slate-900 dark:text-white">{Number(value).toLocaleString()}</p></div>)}</div><div className="grid gap-6 xl:grid-cols-[1.1fr_0.9fr]"><section className="panel overflow-hidden"><div className="border-b border-slate-100 px-6 py-5 dark:border-slate-700"><p className="eyebrow">CRM directory</p><h2 className="mt-1 text-lg font-semibold text-slate-900 dark:text-white">Users and accounts</h2></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{data.users.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 px-6 py-4"><div><p className="font-semibold text-slate-900 dark:text-white">{item.name}</p><p className="text-xs text-slate-500">{item.email}</p></div><div className="text-right text-xs text-slate-400"><p>{item.organization_name || "No workspace"}</p><p>{item.organization_count} workspace{item.organization_count === 1 ? "" : "s"}{item.is_super_admin ? " · Super admin" : ""}</p></div></div>)}</div></section><section className="panel overflow-hidden"><div className="border-b border-slate-100 px-6 py-5 dark:border-slate-700"><p className="eyebrow">Customer CRM</p><h2 className="mt-1 text-lg font-semibold text-slate-900 dark:text-white">Organizations</h2></div><div className="divide-y divide-slate-100 dark:divide-slate-800">{data.organizations.map((item) => <div key={item.id} className="px-6 py-4"><p className="font-semibold text-slate-900 dark:text-white">{item.name}</p><p className="mt-1 text-xs text-slate-500">{item.member_count} members · {item.post_count} collected posts</p><p className="mt-1 text-[10px] uppercase tracking-wider text-slate-400">Created {new Date(item.created_at).toLocaleDateString()}</p></div>)}</div></section></div></>}</main></div>;
}