"use client";

import { FormEvent, useEffect, useState } from "react";
import Sidebar from "@/components/Sidebar";

export default function TeamPage() {
  const [team, setTeam] = useState<{ organization: string; role: string; userId: number; members: { id: number; name: string; email: string; role: string }[] } | null>(null);
  const [email, setEmail] = useState("");
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  async function load() { const response = await fetch("/api/team"); const data = await response.json(); if (!response.ok) setError(data.error); else setTeam(data); }
  useEffect(() => { load(); }, []);
  async function invite(event: FormEvent) { event.preventDefault(); setError(null); setMessage(null); const response = await fetch("/api/team", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email }) }); const data = await response.json(); if (!response.ok) setError(data.error); else { setMessage(data.emailSent ? "Invitation sent." : `Invitation created. Share this link: ${data.inviteUrl}`); setEmail(""); } }
  async function changeRole(userId: number, role: string) { const response = await fetch("/api/team", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ userId, role }) }); const data = await response.json(); if (!response.ok) setError(data.error); else load(); }
  async function removeMember(userId: number) { if (!window.confirm("Remove this member from the workspace?")) return; const response = await fetch(`/api/team?userId=${userId}`, { method: "DELETE" }); const data = await response.json(); if (!response.ok) setError(data.error); else load(); }
  return <div className="min-h-screen lg:pl-64"><Sidebar /><main className="mx-auto min-h-screen max-w-[1100px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><header className="mb-8"><p className="eyebrow">Workspace access</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-900">Team</h1><p className="mt-2 text-sm text-slate-500">{team?.organization || "Your workspace"} · Manage members and invitations.</p></header>{error && <div className="mb-6 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}{message && <div className="mb-6 rounded-xl bg-emerald-50 p-4 text-sm text-emerald-700">{message}</div>}<div className="grid gap-6 md:grid-cols-[0.8fr_1.2fr]"><section className="panel p-6"><p className="eyebrow">Invite member</p><h2 className="mt-1 text-lg font-semibold text-slate-900">Grow your workspace</h2><form onSubmit={invite} className="mt-5 space-y-4"><input required type="email" className="field" placeholder="colleague@company.com" value={email} onChange={(e) => setEmail(e.target.value)} /><button disabled={team?.role !== "admin"} className="w-full rounded-xl bg-blue-600 px-4 py-3 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-40">Send invitation</button></form><p className="mt-4 text-xs leading-relaxed text-slate-400">Invitations expire after 7 days. Configure Resend to email them automatically.</p></section><section className="panel overflow-hidden"><div className="border-b border-slate-100 px-6 py-5"><p className="eyebrow">Members</p><h2 className="mt-1 text-lg font-semibold text-slate-900">Workspace access</h2></div><div className="divide-y divide-slate-100">{team?.members.map((member) => <div key={member.id} className="flex items-center justify-between gap-3 px-6 py-4"><div><strong className="text-sm text-slate-800">{member.name}</strong><p className="text-xs text-slate-400">{member.email}</p></div><div className="flex items-center gap-2"><select disabled={team.role !== "admin" || member.id === team.userId} value={member.role} onChange={(e) => changeRole(member.id, e.target.value)} className="select-field py-1 text-xs"><option value="member">Member</option><option value="admin">Admin</option></select>{team.role === "admin" && member.id !== team.userId && <button onClick={() => removeMember(member.id)} className="text-xs font-semibold text-red-600">Remove</button>}</div></div>)}</div></section></div></main></div>;
}
